---
- name: Persist generated secrets
  ansible.builtin.copy:
    content: "{{ app_generated_secrets | to_nice_yaml }}"
    dest: "{{ app_project_dir }}/.generated-secrets.yml"
    owner: root
    group: root
    mode: "0600"
  no_log: true
